version: '2'

volumes:

  letsencrypt-data:
      driver: '${VOLUME_DRIVER}'

services:

  letsencrypt:
    image: 'vxcontrol/rancher-letsencrypt:v1.0.0'
    environment:
      EULA: '${EULA}'
      API_VERSION: '${API_VERSION}'
      CERT_NAME: '${CERT_NAME}'
      EMAIL: '${EMAIL}'
      DOMAINS: '${DOMAINS}'
      PUBLIC_KEY_TYPE: '${PUBLIC_KEY_TYPE}'
      RENEWAL_TIME: '${RENEWAL_TIME}'
      PROVIDER: '${PROVIDER}'
      DNS_RESOLVERS: '${DNS_RESOLVERS}'
      RENEWAL_PERIOD_DAYS: '${RENEWAL_PERIOD_DAYS}'
      RUN_ONCE: '${RUN_ONCE}'
    volumes:
      - '/var/lib/rancher:/var/lib/rancher'
      - 'letsencrypt-data:/etc/letsencrypt'
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'
      {{- if eq .Values.RUN_ONCE "true" }}
      io.rancher.container.start_once: 'true'
      {{- end }}
