.catalog:

  name: 'Nextcloud'
  version: '20.0.0-0'
  description: |
    The self-hosted productivity platform that keeps you in control.
  uuid: 'fb463349-7bac-410b-8823-39a71aba7cf5'
  minimum_rancher_version: 'v1.6.30'

  questions:

    - variable: 'MYSQL_ROOT_PASSWORD'
      label: 'MySQL root password'
      description: |
        The MySQL root password.
      type: 'password'
      default: ''
      required: true
    - variable: 'MYSQL_PASSWORD'
      label: 'Database password'
      description: |
        The password of the Nextcloud database.
      type: 'password'
      default: ''
      required: true
    - variable: 'VOLUME_DRIVER'
      label: 'Volume driver'
      description: |
        The Volume driver that is being used for persistent storage.
      type: 'enum'
      options:
        - 'local'
      default: 'local'
      required: true
