name: 'GitLab Community Edition'
description: |
  GitLab is a single application for the entire software development lifecycle.
  From project planning and source code management to CI/CD, monitoring, and security.
version: '12.4.0-ce.0'
category: 'Version control'
maintainer: 'Johannes Schmölz'
license: 'MIT License'
projectURL: 'https://github.com/jschmoelz/rancher-catalog'
