.catalog:

  name: 'Nextcloud'
  version: '19.0.4-0'
  description: |
    The self-hosted productivity platform that keeps you in control.
  uuid: 'a172dae3-b57c-4da6-8101-c54921706bad'
  minimum_rancher_version: 'v1.6.26'

  questions:

    - variable: 'MYSQL_ROOT_PASSWORD'
      label: 'MySQL root password'
      description: |
        The MySQL root password.
      type: 'password'
      default: ''
      required: true
    - variable: 'MYSQL_PASSWORD'
      label: 'Database password'
      description: |
        The password of the Nextcloud database.
      type: 'password'
      default: ''
      required: true
    - variable: 'VOLUME_DRIVER'
      label: 'Volume driver'
      description: |
        The Volume driver that is being used for persistent storage.
      type: 'enum'
      options:
        - 'local'
      default: 'local'
      required: true
